disabled_rules:
  - closure_body_length
  - convenience_type
  - custom_rules
  - cyclomatic_complexity
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - explicit_acl
  - explicit_top_level_acl
  - explicit_type_interface
  - extension_access_modifier
  - file_length
  - file_name
  - function_body_length
  - function_parameter_count
  - line_length
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - no_grouping_extension
  - prohibited_interface_builder
  - required_deinit
  - trailing_closure
  - type_body_length
  - vertical_whitespace_opening_braces
opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_enum_raw_value
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - inert_defer
  - joined_default_parameter
  - last_where
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - missing_docs
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - number_separator
  - no_extension_access_modifier
  - nslocalizedstring_key
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_control_flow_label
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - xct_specific_matcher
  - yoda_condition
excluded:
  - Example
  - InternalTest
  - Pods
  - AmazonFreeRTOS/SwiftCBOR
analyzer_rules:
  - unused_import
  - unused_private_declaration