disabled_rules:
  - closure_body_length
  - convenience_type
  - cyclomatic_complexity
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - explicit_acl
  - explicit_top_level_acl
  - explicit_type_interface
  - file_length
  - function_body_length
  - function_parameter_count
  - line_length
  - lower_acl_than_parent
  - multiline_arguments
  - multiline_function_chains
  - no_grouping_extension
  - prohibited_interface_builder
  - trailing_closure
  - type_body_length
opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_enum_raw_value
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - implicit_return
  - implicitly_unwrapped_optional
  - inert_defer
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - missing_docs
  - modifier_order
  - multiline_parameters
  - nimble_operator
  - number_separator
  - no_extension_access_modifier
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - strict_fileprivate
  - switch_case_on_newline
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - yoda_condition
excluded:
  - Pods
analyzer_rules:
  - unused_import

identifier_name:
  excluded:
    - Ok
    - off
    - on
    - afrCentralManagerDidFailToConnectPeripheral