platform :ios, '11.0'
use_frameworks!

target 'AmazonFreeRTOSDemo' do
  pod 'Alertift'
  pod 'AmazonFreeRTOS', :path => '../../'
  pod 'AWSAuthUI'
  pod 'AWSUserPoolsSignIn'
  pod 'LicensePlist'
  pod 'SwiftFormat/CLI'
  pod 'SwiftLint'
end
