platform :ios, '14.1'
use_frameworks!
target 'AmazonFreeRTOSDemo' do
  pod 'Alertift'
  pod 'AmazonFreeRTOS', :path => '../../'
  pod 'AWSAuthUI'
  pod 'AWSMobileClient','~> 2.17.0'
  pod 'AWSUserPoolsSignIn'
  pod 'LicensePlist'
  pod 'SwiftFormat/CLI'
  pod 'SwiftLint'
end
